# tmux theme - generated by omarchy-theme-set

# Status bar
set -g status-style "bg={{ background }},fg={{ foreground }}"
set -g status-left-style "bg={{ color8 }},fg={{ foreground }},bold"
set -g status-right-style "bg={{ color8 }},fg={{ foreground }}"

# Window status
setw -g window-status-style "bg={{ background }},fg={{ foreground }}"
setw -g window-status-current-style "bg={{ color8 }},fg={{ accent }},bold"

# Pane borders
set -g pane-border-style "fg={{ color8 }}"
set -g pane-active-border-style "fg={{ accent }}"

# Message / command bar
set -g message-style "bg={{ color8 }},fg={{ foreground }}"
set -g message-command-style "bg={{ color8 }},fg={{ foreground }}"

# Copy mode selection
setw -g mode-style "bg={{ selection_background }},fg={{ selection_foreground }}"

# Clock
setw -g clock-mode-colour "{{ accent }}"
